import { createStore } from 'redux';
import PokeData from '../components/PokeData';


const initialState = {
  pokemon: [
    {
      "id": 1,
      "name_pokemon": "Bulbasaur",
      "experience_growt": 1059860,
      "attack": 49,
      "defense": 49,
      "sp_attack": 65,
      "sp_defense": 65,
      "speed": 45,
      "hp": 45,
      "abilities": "['Overgrow', 'Chlorophyll']",
      "generation": 1,
      "is_legendary": 0,
      "predict_is_legendary_2": 0,
      "fuerza_IV": 14,
      "type1": "grass",
      "type2": "poison"
    },
    {
      "id": 2,
      "name_pokemon": "Ivysaur",
      "experience_growt": 1059860,
      "attack": 62,
      "defense": 63,
      "sp_attack": 80,
      "sp_defense": 80,
      "speed": 60,
      "hp": 60,
      "abilities": "['Overgrow', 'Chlorophyll']",
      "generation": 1,
      "is_legendary": 0,
      "predict_is_legendary_2": 0,
      "fuerza_IV": 18,
      "type1": "grass",
      "type2": "poison"
    },
    {
      "id": 3,
      "name_pokemon": "Venusaur",
      "experience_growt": 1059860,
      "attack": 100,
      "defense": 123,
      "sp_attack": 122,
      "sp_defense": 120,
      "speed": 80,
      "hp": 80,
      "abilities": "['Overgrow', 'Chlorophyll']",
      "generation": 1,
      "is_legendary": 0,
      "predict_is_legendary_2": 0,
      "fuerza_IV": 28,
      "type1": "grass",
      "type2": "poison"
    },
    {
      "id": 4,
      "name_pokemon": "Charmander",
      "experience_growt": 1059860,
      "attack": 52,
      "defense": 43,
      "sp_attack": 60,
      "sp_defense": 50,
      "speed": 65,
      "hp": 39,
      "abilities": "['Blaze', 'Solar Power']",
      "generation": 1,
      "is_legendary": 0,
      "predict_is_legendary_2": 0,
      "fuerza_IV": 15,
      "type1": "fire",
      "type2": ""
    },
    {
      "id": 5,
      "name_pokemon": "Charmeleon",
      "experience_growt": 1059860,
      "attack": 64,
      "defense": 58,
      "sp_attack": 80,
      "sp_defense": 65,
      "speed": 80,
      "hp": 58,
      "abilities": "['Blaze', 'Solar Power']",
      "generation": 1,
      "is_legendary": 0,
      "predict_is_legendary_2": 0,
      "fuerza_IV": 19,
      "type1": "fire",
      "type2": ""
    },
    {
      "id": 6,
      "name_pokemon": "Charizard",
      "experience_growt": 1059860,
      "attack": 104,
      "defense": 78,
      "sp_attack": 159,
      "sp_defense": 115,
      "speed": 100,
      "hp": 78,
      "abilities": "['Blaze', 'Solar Power']",
      "generation": 1,
      "is_legendary": 0,
      "predict_is_legendary_2": 0,
      "fuerza_IV": 26,
      "type1": "fire",
      "type2": "flying"
    },
    {
      "id": 7,
      "name_pokemon": "Squirtle",
      "experience_growt": 1059860,
      "attack": 48,
      "defense": 65,
      "sp_attack": 50,
      "sp_defense": 64,
      "speed": 43,
      "hp": 44,
      "abilities": "['Torrent', 'Rain Dish']",
      "generation": 1,
      "is_legendary": 0,
      "predict_is_legendary_2": 0,
      "fuerza_IV": 14,
      "type1": "water",
      "type2": ""
    },
    {
      "id": 8,
      "name_pokemon": "Wartortle",
      "experience_growt": 1059860,
      "attack": 63,
      "defense": 80,
      "sp_attack": 65,
      "sp_defense": 80,
      "speed": 58,
      "hp": 59,
      "abilities": "['Torrent', 'Rain Dish']",
      "generation": 1,
      "is_legendary": 0,
      "predict_is_legendary_2": 0,
      "fuerza_IV": 19,
      "type1": "water",
      "type2": ""
    },
    {
      "id": 9,
      "name_pokemon": "Blastoise",
      "experience_growt": 1059860,
      "attack": 103,
      "defense": 120,
      "sp_attack": 135,
      "sp_defense": 115,
      "speed": 78,
      "hp": 79,
      "abilities": "['Torrent', 'Rain Dish']",
      "generation": 1,
      "is_legendary": 0,
      "predict_is_legendary_2": 0,
      "fuerza_IV": 27,
      "type1": "water",
      "type2": ""
    },
    {
      "id": 10,
      "name_pokemon": "Caterpie",
      "experience_growt": 1000000,
      "attack": 30,
      "defense": 35,
      "sp_attack": 20,
      "sp_defense": 20,
      "speed": 45,
      "hp": 45,
      "abilities": "['Shield Dust', 'Run Away']",
      "generation": 1,
      "is_legendary": 0,
      "predict_is_legendary_2": 0,
      "fuerza_IV": 11,
      "type1": "bug",
      "type2": ""
    }
  ]
}

const reducerPokemon = (state = initialState, action) => {
  
  return state
}

export default createStore(reducerPokemon)